### ISSUE TITLE
css_rcon maps *  doesnt work

### ISSUE THREAD

**Issue by Niedes** [LordFetznschaedl/CS2Rcon#3] opened 2023-11-29 16:37 UTC
Hello,
it seems to me that the command `maps *` doesn't work, neither via console using `css_rcon maps *` nor via chat using '`!rcon maps *`'.
Could you please have a look at it?

**Comment by LordFetznschaedl** [comment] 2023-11-29 16:57
Hello @Niedes , 

Just to confirm: You wanted to execute the command to see what maps exist on the server and you thought you would receive a response from the command?

I have tested the maps * command using CS2Rcon and it works. 
The map list is being printed to the server console. The issue is that with CounterStrikeSharp you dont get any response from executing a server command. For that reason I cant change anything until a response is given by CSS.

Regards, 
Robert

**Comment by Niedes** [comment] 2023-11-29 17:30
> and you thought you would receive a response from the command?

Yes, this was what I had expected, thank you for clarification!

**Comment by LordFetznschaedl** [comment] 2023-11-29 17:56
I will close this issue now. 
As soon as there is a way to get a response from commands I will be implementing it.

Regards, 
Robert

**Closed as completed by LordFetznschaedl** 2023-11-29 17:56 UTC
Labels: wontfix
